---
api:
  debug: True
  root_path: ""
  prefix: "/v1"

cors:
  allow_origins: "*"
  allow_credentials: True
  allow_methods: "*"
  allow_headers: "*"

core:
  logging:
    version: 1
    disable_existing_loggers: false
    formatters:
      formatter:
        format: "[%(asctime)s] [%(levelname)s] [%(name)s]: %(message)s"
    handlers:
      console:
        class: "logging.StreamHandler"
        level: "DEBUG"
        formatter: "formatter"
        stream: "ext://sys.stderr"
    root:
      level: "INFO"
      handlers: ["console"]

telegram:
  token: <token>
  webhooks:
    - id: <webhook-id>
      chat_ids:
        - 123456789
        - 987654321

sentry:
  secret: <secret>
